enableGlobalCache: true
changesetBaseRefs: [
  "main",
  "origin/main",
  "upstream/main",
  "dev",
  "origin/dev",
  "upstream/dev",
]
compressionLevel: "mixed"
enableColors: true
enableConstraintsChecks: true
enableTelemetry: false
globalFolder: "${HOME}/.yarn/berry"
injectEnvironmentFiles: [
".env",
".env.local?",
]
