version: '3.8'
name: dds-dev
services:
  frontend:
    image: node:14
    working_dir: /app
    command: bash -c "npm install && npm run dev"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    networks:
      - dds-dev-net
    environment:
      - CHOKIDAR_USEPOLLING=true
      - FAST_REFRESH=false

  backend:
    image: python:3.11
    working_dir: /app
    command: bash -c "pip install -e . && gunicorn --log-level debug ddsurveys.wsgi:app --bind 0.0.0.0:4000 --reload"
    volumes:
      - .:/app
    ports:
      - 4000:4000
      - 4444:4444
    depends_on:
      - db
    networks:
      - dds-dev-net

  db:
    image: mariadb:latest
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=dds
    networks:
      - dds-dev-net

networks:
  dds-dev-net:
    name: dds-dev-net
