version: "3.8"
name: dds
services:
  ddsurveys:
    build: .
    restart: on-failure:5
    volumes:
      - .:/app
    ports:
      - "4000:4000" # to be removed
    expose:
      - "4000"
    depends_on:
      - db
    networks:
      - net

  nginx:
    image: nginx:latest
    restart: on-failure:5
    volumes:
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/letsencrypt
      - ./frontend/build:/var/www/frontend
      - ./volumes/self-signed-ssl:/etc/self-signed-ssl
      - ./volumes/nginx/nginx-entrypoint.sh:/nginx-entrypoint.sh
    ports:
      - "443:443"
      - "80:80"
    entrypoint: /nginx-entrypoint.sh
    depends_on:
      - ddsurveys
    networks:
      - net

  certbot:
    image: certbot/certbot
    volumes:
      - ./volumes/certbot/conf:/etc/letsencrypt
      - ./volumes/certbot/www:/var/www/letsencrypt
      - ./volumes/certbot/certbot-entrypoint.sh:/certbot-entrypoint.sh
    entrypoint: "/certbot-entrypoint.sh"
    networks:
      - net

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dds
    volumes:
      - ./volumes/db:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
     - "3306"
    networks:
      - net

networks:
  net:
    external: false
