"""Move survey platform fields into the project json field

Revision ID: 30fd4d9401eb
Revises: ea9752b24acf
Create Date: 2023-10-04 12:29:42.381534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30fd4d9401eb'
down_revision = 'ea9752b24acf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'survey_name')
    op.drop_column('project', 'survey_id')
    op.drop_column('project', 'survey_platform_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('survey_platform_api_key', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('project', sa.Column('survey_id', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('project', sa.Column('survey_name', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
