"""rem connected field data connections.

Revision ID: 47e9170725eb
Revises: daf7e3007775
Create Date: 2024-03-18 09:22:42.338723

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "47e9170725eb"
down_revision = "daf7e3007775"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("data_connection", "data_provider_type")
    op.drop_column("data_connection", "connected")
    op.alter_column(
        "data_provider",
        "data_provider_type",
        existing_type=mysql.VARCHAR(length=255),
        type_=sa.Enum("generic", "oauth", "frontend", name="dataprovidertype"),
        existing_nullable=True,
    )
    op.drop_column("data_provider_access", "data_provider_type")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "data_provider_access",
        sa.Column(
            "data_provider_type",
            mysql.ENUM("generic", "oauth", "frontend"),
            nullable=True,
        ),
    )
    op.alter_column(
        "data_provider",
        "data_provider_type",
        existing_type=sa.Enum("generic", "oauth", "frontend", name="dataprovidertype"),
        type_=mysql.VARCHAR(length=255),
        existing_nullable=True,
    )
    op.add_column(
        "data_connection",
        sa.Column(
            "connected",
            mysql.TINYINT(display_width=1),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "data_connection",
        sa.Column(
            "data_provider_type",
            mysql.ENUM("generic", "oauth", "frontend"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
