"""project_status to survey_status

Revision ID: 8ff18ebf7f7f
Revises: b5bfb7d24579
Create Date: 2023-09-05 15:37:13.406648

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8ff18ebf7f7f'
down_revision = 'b5bfb7d24579'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('survey_status', sa.Enum('Active', 'Inactive', 'Unknown', name='projectstatus'), nullable=False))
    op.drop_column('project', 'project_status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project', sa.Column('project_status', mysql.ENUM('Active', 'Inactive'), nullable=False))
    op.drop_column('project', 'survey_status')
    # ### end Alembic commands ###
