"""Initial database schema.

Revision ID: 991bc07484f8
Revises:
Create Date: 2024-03-06 10:31:19.713267

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "991bc07484f8"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_provider",
        sa.Column(
            "data_provider_type",
            sa.Enum("Fitbit", "Instagram", "GitHub", "DDS", "GoogleContacts", name="dataprovidertype"),
            nullable=False,
        ),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("data_provider_type"),
    )
    op.create_table(
        "distribution",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("url", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("short_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column(
            "survey_status",
            sa.Enum("Active", "Inactive", "Unknown", name="surveystatus"),
            nullable=False,
        ),
        sa.Column("survey_platform_name", sa.String(length=255), nullable=True),
        sa.Column("survey_platform_fields", sa.JSON(), nullable=True),
        sa.Column("creation_date", sa.DateTime(), nullable=True),
        sa.Column("last_modified", sa.DateTime(), nullable=True),
        sa.Column("last_synced", sa.DateTime(), nullable=True),
        sa.Column("variables", sa.JSON(), nullable=True),
        sa.Column("custom_variables", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "researcher",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("firstname", sa.String(length=255), nullable=True),
        sa.Column("lastname", sa.String(length=255), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("password", sa.String(length=512), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "collaboration",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("researcher_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["researcher_id"], ["researcher.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("project_id", "researcher_id"),
    )
    op.create_table(
        "data_connection",
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column(
            "data_provider_type",
            sa.Enum("Fitbit", "Instagram", "GitHub", "DDS", "GoogleContacts", name="dataprovidertype"),
            nullable=False,
        ),
        sa.Column("connected", sa.Boolean(), nullable=True),
        sa.Column("fields", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_provider_type"],
            ["data_provider.data_provider_type"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("project_id", "data_provider_type"),
    )
    op.create_table(
        "respondent",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("distribution_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["distribution_id"], ["distribution.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "data_provider_access",
        sa.Column(
            "data_provider_type",
            sa.Enum("Fitbit", "Instagram", "GitHub", "DDS", "GoogleContacts", name="dataprovidertype"),
            nullable=False,
        ),
        sa.Column("user_id", sa.String(length=255), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("respondent_id", sa.String(length=36), nullable=False),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["data_provider_type"],
            ["data_provider.data_provider_type"],
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["respondent_id"], ["respondent.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint(
            "data_provider_type", "user_id", "project_id", "respondent_id"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_provider_access")
    op.drop_table("respondent")
    op.drop_table("data_connection")
    op.drop_table("collaboration")
    op.drop_table("researcher")
    op.drop_table("project")
    op.drop_table("distribution")
    op.drop_table("data_provider")
    # ### end Alembic commands ###
