"""survey_status

Revision ID: da503e3b823b
Revises: 8ff18ebf7f7f
Create Date: 2023-09-05 15:38:49.077926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da503e3b823b'
down_revision = '8ff18ebf7f7f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
