name: Run Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_ddsurveys_tests:
    name: Run ddsurveys pytest tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Setup Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      # Install dependencies
      - name: Install ddsurveys
        run: |
          python -m pip install --upgrade pip
          pip install -e .  # Install your package in editable mode

      # Run tests
      - name: Run pytest tests
        run: |
          python -m pytest -v
